version: "3.7"

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - elasticsearch
      - mongo
      - postgres
      - redis
    ports:
      - 8000:8000
    restart: always

  elasticsearch:
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    restart: always
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  grafana:
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    image: grafana/grafana:6.4.3
    ports:
      - 3000:3000
    restart: always

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.8.2
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibana:/usr/share/kibana/config

  mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  mongo_express:
    depends_on:
      - mongo
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    restart: always

  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:10.5
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbit:
    build:
      context: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis:/data

  scraper_gatherer:
    build:
      context: .
      dockerfile: scraper_gatherer/Dockerfile
    depends_on:
      - mongo
      - rabbit
    restart: always
    volumes:
      - scraper_gatherer:/data

  scraper_mtg:
    build:
      context: .
      dockerfile: scraper_mtg/Dockerfile
    depends_on:
      - mongo
      - rabbit
    restart: always
    volumes:
      - dev:/data

  selenium_hub:
    image: selenium/hub:3.141.59
    restart: always

  selenium_node_chrome:
    depends_on:
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - SE_OPTS=-browserTimeout 60 -timeout 60 -cleanUpCycle 60
    image: selenium/node-chrome:3.141.59
    restart: always

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - api
      - static
    ports:
      - 80:80
    restart: always

  static:
    build:
      context: .
      dockerfile: static/Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - scraper_gatherer:/data:ro

  vault:
    image: vault:1.2.3
    restart: always

volumes:
  dev:
  elasticsearch:
  kibana:
  mongo_configdb:
  mongo_db:
  postgres:
  rabbit:
  redis:
  scraper_gatherer:
