version: '3.7'

networks:

  default:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - elasticsearch
      - mongo
      - postgres
      - redis
    env_file:
      - .env
    healthcheck:
      interval: 10s
      retries: 2
      test: ['CMD', 'curl', '-f', 'http://${API_HOST}:${API_PORT}/v1/healthcheck']
      timeout: 2s
    networks:
      default:
        ipv4_address: ${API_HOST}
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped

  consul:
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir /data
    entrypoint: /bin/consul
    env_file:
      - .env
    image: consul:1.6.3
    networks:
      default:
        ipv4_address: ${CONSUL_HOST}
    ports:
      - ${CONSUL_PORT}:${CONSUL_PORT}
    restart: unless-stopped
    volumes:
      - consul:/data

  elasticsearch:
    env_file:
      - .env
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    networks:
      default:
        ipv4_address: ${ELASTIC_HOST}
    restart: unless-stopped
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    env_file:
      - .env
    image: docker.elastic.co/kibana/kibana:7.5.2
    networks:
      default:
        ipv4_address: ${KIBANA_HOST}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    restart: unless-stopped
    volumes:
      - kibana:/usr/share/kibana/config

  mock:
    build:
      context: .
      dockerfile: mock/Dockerfile
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${MOCK_HOST}
    restart: unless-stopped

  mongo:
    env_file:
      - .env
    image: mongo:4.2.0
    networks:
      default:
        ipv4_address: ${MONGO_HOST}
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  mongo_express:
    depends_on:
      - mongo
    env_file:
      - .env
    image: mongo-express:0.49.0
    networks:
      default:
        ipv4_address: ${MONGO_EXPRESS_HOST}
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    restart: unless-stopped

  postgres:
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:10.5
    networks:
      default:
        ipv4_address: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbit:
    build:
      context: rabbit
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${RABBIT_HOST}
    ports:
      - 15672:15672
    restart: unless-stopped
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    env_file:
      - .env
    image: redis:5.0.5
    networks:
      default:
        ipv4_address: ${REDIS_HOST}
    restart: unless-stopped
    volumes:
      - redis:/data

  scraper_gatherer:
    build:
      context: .
      dockerfile: scraper_gatherer/Dockerfile
    depends_on:
      - mongo
      - rabbit
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - scraper_gatherer:/data

  scraper_downloader:
    build:
      context: .
      dockerfile: scraper_downloader/Dockerfile
    depends_on:
      - elasticsearch
      - mongo
      - rabbit
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - scraper_mtg:/data

  scraper_indexer:
    build:
      context: .
      dockerfile: scraper_indexer/Dockerfile
    depends_on:
      - elasticsearch
      - mongo
      - rabbit
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - scraper_mtg:/data

  scraper_parser:
    build:
      context: .
      dockerfile: scraper_parser/Dockerfile
    depends_on:
      - elasticsearch
      - mongo
      - rabbit
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - scraper_mtg:/data

  selenium_hub:
    env_file:
      - .env
    image: selenium/hub:3.141.59
    restart: unless-stopped

  selenium_node_chrome:
    depends_on:
      - selenium_hub
    env_file:
      - .env
    environment:
      - HUB_HOST=selenium_hub
      - SE_OPTS=-browserTimeout 60 -timeout 60 -cleanUpCycle 60
    image: selenium/node-chrome:3.141.59
    restart: unless-stopped

  static:
    build:
      context: .
      dockerfile: static/Dockerfile
    env_file:
      - .env
    networks:
      default:
        ipv4_address: ${STATIC_HOST}
    restart: unless-stopped
    volumes:
      - scraper_gatherer:/data:ro

  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    depends_on:
      - elasticsearch
    env_file:
      - .env
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - api
      - static
    env_file:
      - .env
    healthcheck:
      interval: 10s
      retries: 2
      test: ['CMD', 'curl', '-f', 'http://localhost:${UI_PORT}']
      timeout: 2s
    networks:
      default:
        ipv4_address: ${UI_HOST}
    ports:
      - ${UI_PORT}:${UI_PORT}
    restart: unless-stopped

volumes:
  consul:
  elasticsearch:
  kibana:
  mongo_configdb:
  mongo_db:
  postgres:
  rabbit:
  redis:
  scraper_gatherer:
  scraper_mtg:
