"""empty message

Revision ID: 401e07e7995f
Revises: 011af6f49837
Create Date: 2019-10-27 00:36:06.895441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '401e07e7995f'
down_revision = '011af6f49837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decks', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('decks', 'owner_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('decks', 'owner_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('decks', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
