"""empty message

Revision ID: fb0eec2f939a
Revises: 
Create Date: 2019-09-05 06:18:55.914789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0eec2f939a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('mana', sa.String(length=200), nullable=True),
    sa.Column('converted_mana_cost', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('flavor', sa.String(length=200), nullable=True),
    sa.Column('watermark', sa.String(length=200), nullable=True),
    sa.Column('power', sa.String(length=200), nullable=True),
    sa.Column('toughness', sa.String(length=200), nullable=True),
    sa.Column('loyalty', sa.String(length=200), nullable=True),
    sa.Column('set', sa.String(length=200), nullable=True),
    sa.Column('rarity', sa.String(length=200), nullable=True),
    sa.Column('number', sa.String(length=200), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_artist'), 'card', ['artist'], unique=True)
    op.create_index(op.f('ix_card_converted_mana_cost'), 'card', ['converted_mana_cost'], unique=True)
    op.create_index(op.f('ix_card_flavor'), 'card', ['flavor'], unique=True)
    op.create_index(op.f('ix_card_loyalty'), 'card', ['loyalty'], unique=True)
    op.create_index(op.f('ix_card_mana'), 'card', ['mana'], unique=True)
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=True)
    op.create_index(op.f('ix_card_number'), 'card', ['number'], unique=True)
    op.create_index(op.f('ix_card_power'), 'card', ['power'], unique=True)
    op.create_index(op.f('ix_card_rarity'), 'card', ['rarity'], unique=True)
    op.create_index(op.f('ix_card_set'), 'card', ['set'], unique=True)
    op.create_index(op.f('ix_card_text'), 'card', ['text'], unique=True)
    op.create_index(op.f('ix_card_toughness'), 'card', ['toughness'], unique=True)
    op.create_index(op.f('ix_card_type'), 'card', ['type'], unique=True)
    op.create_index(op.f('ix_card_watermark'), 'card', ['watermark'], unique=True)
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_format_name'), 'format', ['name'], unique=True)
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_name'), 'set', ['name'], unique=True)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_name'), 'type', ['name'], unique=True)
    op.create_table('card_format',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['format.id'], )
    )
    op.create_table('card_set',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], )
    )
    op.create_table('card_type',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_type')
    op.drop_table('card_set')
    op.drop_table('card_format')
    op.drop_index(op.f('ix_type_name'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_set_name'), table_name='set')
    op.drop_table('set')
    op.drop_index(op.f('ix_format_name'), table_name='format')
    op.drop_table('format')
    op.drop_index(op.f('ix_card_watermark'), table_name='card')
    op.drop_index(op.f('ix_card_type'), table_name='card')
    op.drop_index(op.f('ix_card_toughness'), table_name='card')
    op.drop_index(op.f('ix_card_text'), table_name='card')
    op.drop_index(op.f('ix_card_set'), table_name='card')
    op.drop_index(op.f('ix_card_rarity'), table_name='card')
    op.drop_index(op.f('ix_card_power'), table_name='card')
    op.drop_index(op.f('ix_card_number'), table_name='card')
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_index(op.f('ix_card_mana'), table_name='card')
    op.drop_index(op.f('ix_card_loyalty'), table_name='card')
    op.drop_index(op.f('ix_card_flavor'), table_name='card')
    op.drop_index(op.f('ix_card_converted_mana_cost'), table_name='card')
    op.drop_index(op.f('ix_card_artist'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
