DATABASE_DRIVER = 'postgresql+psycopg2'
DATABASE_HOST = 'postgres'
DATABASE_NAME = 'dev'
DATABASE_PASSWORD = 'dev'
DATABASE_USER = 'dev'


class Config:
    SQLALCHEMY_DATABASE_URI = '{}://{}:{}@{}/{}'.format(DATABASE_DRIVER, DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_NAME)
    SQLALCHEMY_ECHO = True
    SQLALCHEMY_TRACK_MODIFICATIONS = False
